export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source /usr/local/opt/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f $XDG_CONFIG_HOME/zsh/.p10k.zsh ]] || source $XDG_CONFIG_HOME/zsh/.p10k.zsh


source $XDG_CONFIG_HOME/zsh/zsh-newuser-install.sh
source $XDG_CONFIG_HOME/zsh/compinstall.sh
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source $XDG_CONFIG_HOME/zsh/zsh-completions.sh
source $XDG_CONFIG_HOME/zsh/todo-init.sh
source $XDG_CONFIG_HOME/zsh/aliases.sh
source $XDG_CONFIG_HOME/zsh/locale.sh
source $XDG_CONFIG_HOME/zsh/asdf-python-virtualenvs.sh
source $XDG_CONFIG_HOME/zsh/miniforge-init.sh
source $HOME/.asdf/plugins/java/set-java-home.zsh
